server:
  port: 9004
  
spring:
  application:
    name: springbootadminclient
  boot:
    admin:
      client:
        url: http://172.18.164.251:9999 #注册到admin server，这里是admin server的地址和IP
        instance:
          prefer-ip: true #使用客户端IP进行注册     
               
management:    
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    #shutdown:
      #enabled: true  #这样可以在需要时发送post到服务端，就可以关闭了
     



             
    
   
     
     